add redux-thunk and fix error with name method "createRouterReducer"
titarenko/buhoi-client pull request #1
Opened 2017-03-24 12:42 UTC by akhll

add redux-thunk and fix error with name method "createRouterReducer"

2017-03-24 17:49 UTC, titarenko requested changes

2017-03-24 17:49 UTC, titarenko commented on lib/store.js
> +const reduxThunk = require('redux-thunk').default
what if lib client doesn't want to use redux-thunk?

2017-03-24 17:49 UTC, titarenko commented on lib/navigation.js
> +	createRouterReducer,
make rebase onto up to date version

2017-12-26 12:29 UTC, akhll commented
not relevant

2017-12-26 12:29 UTC, closed without merging